### ISSUE TITLE
Crashes on TealiumLifecycleModule.newWake: outlined init with copy

### ISSUE THREAD

**Issue by Enricoza** [Tealium/tealium-swift#120]
**Your Environment**
Tealium Swift library version [e.g. 1.6.7]: 1.8.0-beta3

**Describe the bug**
A couple of crashes are happening on TealiumLifecycleModule's `newWake`. I report them both here because they might be related.

```
Crashed: com.tealium.backgroundconcurrentqueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000117b44008
0  libswiftCore.dylib             0x1ad316dd0 _swift_retain_(swift::HeapObject*) + 16
1  libswiftCore.dylib             0x1ad35bc5c swift_bridgeObjectRetain + 52
2  TealiumSwift                   0x1039d807c outlined init with copy of TealiumLifecycle? (<compiler-generated>)
3  TealiumSwift                   0x1039d6fe4 TealiumLifecycleModule.track(_:) + 92 (TealiumLifecycleModule.swift:92)
4  TealiumSwift                   0x1039df498 TealiumModule.handle(_:) + 73 (TealiumModule.swift:73)
5  TealiumSwift                   0x1039ecbf0 closure #1 in TealiumModulesManager.tealiumModuleFinished(module:process:) + 194 (TealiumModulesManager.swift:194)
6  TealiumSwift                   0x1039ecab0 TealiumModulesManager.tealiumModuleFinished(module:process:) (<compiler-generated>)
7  TealiumSwift                   0x1039e0088 TealiumModule.didFinishWithNoResponse(_:) (<compiler-generated>)
8  TealiumSwift                   0x1039e0570 TealiumModule.track(_:) + 185 (TealiumModule.swift:185)
9  TealiumSwift                   0x1039df498 TealiumModule.handle(_:) + 73 (TealiumModule.swift:73)
10 TealiumSwift                   0x1039eac98 TealiumModulesManager.track(_:) + 146 (TealiumModulesManager.swift:146)
11 TealiumSwift                   0x10399c734 closure #1 in Tealium.track(title:data:completion:) + 101 (Tealium.swift:101)
12 TealiumSwift                   0x1039f86d0 closure #1 in ReadWrite.barrieredWork(_:) (<compiler-generated>)
13 TealiumSwift                   0x10399cca8 thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
14 libdispatch.dylib              0x19fc21610 _dispatch_call_block_and_release + 24
15 libdispatch.dylib              0x19fc22184 _dispatch_client_callout + 16
16 libdispatch.dylib              0x19fbd600c _dispatch_lane_concurrent_drain + 936
17 libdispatch.dylib              0x19fbceed8 _dispatch_lane_invoke$VARIANT$mp + 548
18 libdispatch.dylib              0x19fbd6fd0 _dispatch_root_queue_drain + 376
19 libdispatch.dylib              0x19fbd779c _dispatch_worker_thread2 + 128
20 libsystem_pthread.dylib        0x19fc71f64 _pthread_wqthread + 212
21 libsystem_pthread.dylib        0x19fc74ae0 start_wqthread + 8
```

```
Crashed: com.tealium.backgroundconcurrentqueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000432b566be0
0  TealiumSwift                   0x1073fb854 outlined init with copy of TealiumLifecycleSession (<compiler-generated>)
1  TealiumSwift                   0x1073f8ca8 TealiumLifecycle.newTrack(at:) (<compiler-generated>)
2  TealiumSwift                   0x107403094 TealiumLifecycleModule.track(_:) + 97 (TealiumLifecycleModule.swift:97)
3  TealiumSwift                   0x10740b498 TealiumModule.handle(_:) + 73 (TealiumModule.swift:73)
4  TealiumSwift                   0x107418bf0 closure #1 in TealiumModulesManager.tealiumModuleFinished(module:process:) + 194 (TealiumModulesManager.swift:194)
5  TealiumSwift                   0x107418ab0 TealiumModulesManager.tealiumModuleFinished(module:process:) (<compiler-generated>)
6  TealiumSwift                   0x10740c088 TealiumModule.didFinishWithNoResponse(_:) (<compiler-generated>)
7  TealiumSwift                   0x10740c570 TealiumModule.track(_:) + 185 (TealiumModule.swift:185)
8  TealiumSwift                   0x10740b498 TealiumModule.handle(_:) + 73 (TealiumModule.swift:73)
9  TealiumSwift                   0x107416c98 TealiumModulesManager.track(_:) + 146 (TealiumModulesManager.swift:146)
10 TealiumSwift                   0x1073c8734 closure #1 in Tealium.track(title:data:completion:) + 101 (Tealium.swift:101)
11 TealiumSwift                   0x1074246d0 closure #1 in ReadWrite.barrieredWork(_:) (<compiler-generated>)
12 TealiumSwift                   0x1073c8ca8 thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
13 libdispatch.dylib              0x1918b6610 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x1918b7184 _dispatch_client_callout + 16
15 libdispatch.dylib              0x19186afe0 _dispatch_lane_concurrent_drain + 936
16 libdispatch.dylib              0x191863e78 _dispatch_lane_invoke$VARIANT$mp + 548
17 libdispatch.dylib              0x19186bfa4 _dispatch_root_queue_drain + 376
18 libdispatch.dylib              0x19186c770 _dispatch_worker_thread2 + 128
19 libsystem_pthread.dylib        0x191906f48 _pthread_wqthread + 212
20 libsystem_pthread.dylib        0x191909ad4 start_wqthread + 8
```

**Expected behavior**
It should not crash.

**Additional context**
The only info that I can add is that I see lots of low memory instance of crashes (around 1% to 7%) in those cases, so might it be related to the structs being too big in those cases? (I'm not sure, )
I'm assuming that using classes instead would solve those crashes (since there won't be no copy 😅) but maybe there's a more profound issue that makes those structs so big in memory? Maybe the safe check to just remove one session from the array doesn't really help if it (somehow) is initiated with a 200 session array?
Anyway I'm just guessing, I didn't have time to investigate or run some test about this issue.

As a side note, this is the third most impactful crash in my reports, but 5 times less impactful than the first 2 (one of which is related to Tealium and it's the one we discussed in the other issue).

**Comment by Enricoza** [comment]
Looking further down in the crashes I saw also this other crash that could be related. It has a very low impact but maybe it can help you understand:

```
Crashed: com.tealium.backgroundconcurrentqueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000119448008
0  libswiftCore.dylib             0x1ba394798 _swift_release_(swift::HeapObject*) + 12
1  TealiumSwift                   0x1033f45c0 outlined destroy of TealiumLifecycle (<compiler-generated>)
2  TealiumSwift                   0x1033fb2e0 TealiumLifecycleModule.track(_:) + 102 (TealiumLifecycleModule.swift:102)
3  TealiumSwift                   0x103403498 TealiumModule.handle(_:) + 73 (TealiumModule.swift:73)
4  TealiumSwift                   0x103410bf0 closure #1 in TealiumModulesManager.tealiumModuleFinished(module:process:) + 194 (TealiumModulesManager.swift:194)
5  TealiumSwift                   0x103410ab0 TealiumModulesManager.tealiumModuleFinished(module:process:) (<compiler-generated>)
6  TealiumSwift                   0x103404088 TealiumModule.didFinishWithNoResponse(_:) (<compiler-generated>)
7  TealiumSwift                   0x103404570 TealiumModule.track(_:) + 185 (TealiumModule.swift:185)
8  TealiumSwift                   0x103403498 TealiumModule.handle(_:) + 73 (TealiumModule.swift:73)
9  TealiumSwift                   0x10340ec98 TealiumModulesManager.track(_:) + 146 (TealiumModulesManager.swift:146)
10 TealiumSwift                   0x1033c0734 closure #1 in Tealium.track(title:data:completion:) + 101 (Tealium.swift:101)
11 TealiumSwift                   0x10341c6d0 closure #1 in ReadWrite.barrieredWork(_:) (<compiler-generated>)
12 TealiumSwift                   0x1033c0ca8 thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
13 libdispatch.dylib              0x1acb72610 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x1acb73184 _dispatch_client_callout + 16
15 libdispatch.dylib              0x1acb26fe0 _dispatch_lane_concurrent_drain + 936
16 libdispatch.dylib              0x1acb1fe78 _dispatch_lane_invoke$VARIANT$mp + 548
17 libdispatch.dylib              0x1acb27fa4 _dispatch_root_queue_drain + 376
18 libdispatch.dylib              0x1acb28770 _dispatch_worker_thread2 + 128
19 libsystem_pthread.dylib        0x1acbc2f48 _pthread_wqthread + 212
20 libsystem_pthread.dylib        0x1acbc5ad4 start_wqthread + 8
```

**Comment by craigrouse** [comment]
@Enricoza As per the other issue, we'll look into this right away. Thanks for your patience.

**Comment by craigrouse** [comment]
@Enricoza as per my comment on the other issue, this is (hopefully) resolved in 1.8.2. See details here: https://github.com/Tealium/tealium-swift/releases/tag/1.8.2. This isn't a guaranteed fix, since we couldn't reproduce it, but hopefully limiting the sessions to 20 should significantly reduce the memory footprint and prevent the low memory crashes you were seeing. Let us know how you get on. Thanks again for your valuable input.

**Comment by Enricoza** [comment]
@craigrouse thanks, I actually like those fixes. 
I'll let you know if this release fixes all the crashes.

**Comment by Enricoza** [comment]
@craigrouse those crashes seems to have disappeared too, but I still see some similar crash even if on some other line:


```
Crashed: com.tealium.backgroundconcurrentqueue
0  TealiumSwift                   0x108203710 outlined init with copy of TealiumLifecycleSession + 32 (<compiler-generated>:32)
1  TealiumSwift                   0x1082010f8 TealiumLifecycle.newTrack(at:) + 168 (<compiler-generated>:168)
2  TealiumSwift                   0x10820ac18 TealiumLifecycleModule.track(_:) + 97 (TealiumLifecycleModule.swift:97)
3  TealiumSwift                   0x108213058 TealiumModule.handle(_:) + 73 (TealiumModule.swift:73)
4  TealiumSwift                   0x10821b2a8 closure #1 in TealiumModulesManager.tealiumModuleFinished(module:process:) + 197 (TealiumModulesManager.swift:197)
5  TealiumSwift                   0x10821b13c TealiumModulesManager.tealiumModuleFinished(module:process:) + 696 (<compiler-generated>:696)
6  TealiumSwift                   0x108213c48 TealiumModule.didFinishWithNoResponse(_:) + 100 (<compiler-generated>:100)
7  TealiumSwift                   0x108214130 TealiumModule.track(_:) + 185 (TealiumModule.swift:185)
8  TealiumSwift                   0x108213058 TealiumModule.handle(_:) + 73 (TealiumModule.swift:73)
9  TealiumSwift                   0x1082192ec TealiumModulesManager.track(_:) + 146 (TealiumModulesManager.swift:146)
10 TealiumSwift                   0x1081cdfac closure #1 in Tealium.track(title:data:completion:) + 119 (Tealium.swift:119)
11 TealiumSwift                   0x10822aefc closure #1 in ReadWrite.barrieredWork(_:) + 108 (<compiler-generated>:108)
12 TealiumSwift                   0x1081ce558 thunk for @escaping @callee_guaranteed () -> () + 28 (<compiler-generated>:28)
13 libdispatch.dylib              0x1b1876610 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x1b1877184 _dispatch_client_callout + 16
15 libdispatch.dylib              0x1b182afe0 _dispatch_lane_concurrent_drain + 936
16 libdispatch.dylib              0x1b1823e78 _dispatch_lane_invoke$VARIANT$mp + 548
17 libdispatch.dylib              0x1b182bfa4 _dispatch_root_queue_drain + 376
18 libdispatch.dylib              0x1b182c770 _dispatch_worker_thread2 + 128
19 libsystem_pthread.dylib        0x1b18c6b48 _pthread_wqthread + 212
20 libsystem_pthread.dylib        0x1b18c9760 start_wqthread + 8
```

I don't yet know if this crash has an high impact or not, but I just wanted to give you a heads up on the current state.

**Comment by christinasund** [comment]
@Enricoza Thank you for the feedback! We will take a look.

**Comment by craigrouse** [comment]
@Enricoza This sounds like it could be memory-related again. We've so far been unable to reproduce it on the simulator, or on real devices. I suspect it may be happening on older hardware with low memory; do you have any further details about the crash yet? Device types and OS version would be particularly interesting, as well as the frequency and volume of the crashes. Thank you.

**Comment by Enricoza** [comment]
Hi @craigrouse, 
yes it could be related to memory even if I'm not sure about it.
Most of the crashes happen on iPhone 7 and 6s (63% of the crashes), and I see a lot of 3-6% ram free crashes.
But I also see some iPhone XS with 20% ram free crashes, so maybe it's not just related to old devices and low memory. If it's actually related to memory it probably means that in some rare cases the memory usage rises a lot.

About the OS, it's 96% iOS 13, but that's common on iOS since users usually update to the newest available OS quite fast.

As a side note, this crash is not new, but (maybe due to the other crashes that were preventing this crash to happen?) it was around 10-15 crashes per week before the update to 1.8.2.
Now (with 80% adoption) we are at 200 of these crashes per week.


Another interesting info is that all the crashes happen on unique users, don't know if that could be useful.

**Comment by craigrouse** [comment]
Thanks for the extra info @Enricoza. We'll continue to see if there are some optimizations we can make in that method. We'll let you know if we need anything else.

**Comment by craigrouse** [comment]
@Enricoza Although we can't reproduce the issue, we've updated the code to avoid mutating the struct in question in the newTrack method, which I *think* should solve the problem, since no copying needs to take place, which should prevent this crash occurring in a low memory scenario. This will be in the next release, which is on the way very soon.

**Comment by craigrouse** [comment]
@Enricoza I'm sure you've seen already that 1.9.0 is released, and we are hoping that this issue is resolved. The mutating method on the Lifecycle struct implicated in the crash log has been changed to non-mutating, which should hopefully alleviate the problem. This is something of an educated guess, though, as we couldn't reproduce your issue, so please monitor and see what your stats show.

Unfortunately, there's been a slight technical issue with the documentation being published (docs.tealium.com/platforms/ios-swift), but this will be resolved later today. Please be sure to read the release notes before upgrading: https://github.com/Tealium/tealium-swift/releases/tag/1.9.0

Will leave this issue open until you confirm it's fixed. Please consider trying our new SPM package as an alternative to CocoaPods/Carthage, if possible. Thank you.

**Comment by Enricoza** [comment]
Thank you @craigrouse, it may take some time before I can get back at you with the results but I'm gonna try the new library ASAP.

About the SPM I think that for the time being I must decline your offer since I myself am using tealium-swift in a (series of) CocoaPod(s) for several apps that all use CocoaPods. Converting all of them to SPM would be quite complicated ATM.

**Comment by craigrouse** [comment]
No problem @Enricoza. We'll obviously continue to support the other package managers, so no rush to migrate. We've been impressed by SPM so far, though, despite a few shortcomings. 🤞 this solves your crash. Thanks.

**Comment by christinasund** [comment]
@Enricoza Closing this for now, but let us know if you have any more feedback. Thanks!
