### ISSUE TITLE
TealiumDispatchQueueExtensions.swift line 138 crash on iOS 15 

### ISSUE THREAD

**Issue by frankdeboer1985** [Tealium/tealium-swift#246]
Dear team,

Using tealium-swift/TealiumFull (2.4.2) on iOS 15 we now get the following crash: TealiumDispatchQueueExtensions.swift line 138

https://openradar.appspot.com/FB9741207
https://twitter.com/steipete/status/1443506043733032962
https://github.com/react-native-device-info/react-native-device-info/issues/1330
https://github.com/DataDog/dd-sdk-ios/issues/609

In our case it seems to be related when initialising NSAttributedString with HTML string. But the crash is happening in Tealium.

Thanks.

**Comment by craigrouse** [comment]
@frankdeboer1985 We updated the SDK recently to fix this issue - https://github.com/Tealium/tealium-swift/releases/tag/2.4.6. Please upgrade to the latest SDK if possible (2.5.1), which also includes some other stability fixes that should prevent crashes in other areas.

Once you've upgraded, you need to set `config.batterySaverEnabled` to `false`, which prevents Tealium from listening for power notifications, which is the source of the crash. 

Please also note that if you were previously using the AutoTracking module, the behavior of this module has changed significantly in 2.5.1. You can check if you're using it by looking at your `config.collectors` property - if `Collectors.AutoTracking` is in the list, then you're using AutoTracking.

**Comment by frankdeboer1985** [comment]
Thanks for the quick response.

**Comment by craigrouse** [comment]
@frankdeboer1985 we just released another SDK update (2.6.0), which includes a permanent fix for the crash and no longer requires the battery saver feature to be disabled.

**Comment by MRodSebastian** [comment]
I have the same crash. I try to update to 2.5.1, set `config.batterySaverEnabled` to `false` and nothing... this bug persist. I hope that 2.6.0 fix this issue.

**Comment by craigrouse** [comment]
I would add that other customers have upgraded and set the `batterySaverEnabled` flag, and it has resolved the issue for them, so I can only assume there's something wrong in your app that's caused the fix not to be effective.

**Comment by MRodSebastian** [comment]
@craigrouse users are updated to the latests version with `config.batterySaverEnabled` to `false`. I will try with `config.shouldUseRemotePublishSettings` to `false` and upgrade Tealium SDK to 2.6.0.
