### ISSUE TITLE
[TEALIUM SWIFT BUG]: Runtime crash on launch with Xcode 15 Release

### ISSUE THREAD

**Issue by mirko-milovanovic-vidiemme** [Tealium/tealium-swift#311]
**Your Environment**
iOS Version(s): 16
Xcode version: Version 15.0 (15A240d)
Swift version: 5.9
Tealium Swift library version:  2.10.1
Dependency manager: CocoaPods
Dependency manager version: 1.12.1

**Describe the bug**
Unable to open iOS application when running in Xcode 15 release version due to the following runtime crash in `tealium-swift/tealium/core/connectivity/NWPathMonitor.swift` with error

```
var monitor = NWPathMonitor() - EXC_BAD_ACCESS (code=1, address=0x0)
```

**Does a workaround exist?**
The error does not appear when building for the simulator, only when building for physical devices

**To Reproduce**
Run any project in Xcode 15 with tealium-swift as a dependency and **building it for a physical device target**.

- git clone https://github.com/Tealium/tealium-swift
- Go to one of the samples cd tealium-swift/samples/TealiumSwiftExample
- Install dependencies pod install
- Open TealiumSwiftExample.xcworkspace with Xcode 15 beta.
- Run the app.
- See runtime crash.

**Expected behavior**
No runtime crash should occur when running a project with tealium-swift as a dependency in Xcode 15.

**Screenshots**
<img width="1792" alt="Screenshot 2023-09-19 alle 10 37 09" src="https://github.com/Tealium/tealium-swift/assets/116636082/5a269922-854d-48da-8016-7447d4e9c76d">

**Additional context**
The issue seems to be in:
https://github.com/Tealium/tealium-swift/blob/26aeb8f13ad755104f252a19a6526d1b54608a8c/tealium/core/connectivity/NWPathMonitor.swift#L37

**Comment by Enricoza** [comment]
Hi @mirko-milovanovic-vidiemme, thank you for opening this. 
I was able to reproduce the issue and I could narrow it down to XCode 15 not supporting iOS 11 anymore. 
We will soon have an official release supporting XCode 15 but for the time being we suggest using XCode 14 for production builds. 
In the meantime you should be able to run an application with our SDK on XCode 15 by updating the Pod deployment target to iOS 12. You can do that manually after each `pod install` or you can add a post_install script in your Podfile like this:

```
post_install do |installer|
 installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
     end
 end
end
``` 

Let me know if you are still encountering issues even after the post install script or if you encounter any other problems that we should address on XCode 15. And thank you again for the report!

**Comment by mirko-milovanovic-vidiemme** [comment]
Awesome, i'll wait for the official release for Xcode 15 then

**Comment by p4checo** [comment]
Hi 👋🏼 

Not sure if related, but I'm having runtime crashes when running a test target that references another target importing Tealium via SPM on Xcode 15. 

Building and running our app with Xcode 15 in both simulator and physical devices doesn't appear to have any issue, only when running this particular test suite.

It seems to be caused by some linker issue:

![Screenshot 2023-09-22 at 18 02 12](https://github.com/Tealium/tealium-swift/assets/1391324/eee28ed4-9d0e-40c4-b001-7ac00241189f)

Our SPM setup consists of a Swift Package that contains a `TealiumAnalytics` target that imports Tealium where we define an analytics tracker. Then we define a corresponding test target `TealiumAnalyticsTests` that only references the latter. The tests are being ran from opening the Swift Package via Xcode, not from any "normal" xcode project.

```swift
        .target(
            name: "TealiumAnalytics",
            dependencies: [
                .product(name: "TealiumCollect", package: "tealium-swift"),
                .product(name: "TealiumCore", package: "tealium-swift"),
                .product(name: "TealiumContentsquare", package: "tealium-ios-contentsquare-remote-command"),
                .product(name: "TealiumFirebase", package: "tealium-ios-firebase-remote-command"),
                .product(name: "TealiumRemoteCommands", package: "tealium-swift"),
                .product(name: "TealiumTagManagement", package: "tealium-swift"),
                .product(name: "TealiumLifecycle", package: "tealium-swift"),
            ],
            path: "Sources/Vendor/TealiumAnalytics"
        ),
        .testTarget(
            name: "TealiumAnalyticsTests",
            dependencies: ["TealiumAnalytics"],
            path: "Tests/Vendor/TealiumAnalyticsTests"
        ),
```

The test does nothing (default implementation), only references the `TealiumAnalytics` module:

```swift
@testable import TealiumAnalytics
import XCTest

final class TealiumAnalyticsTests: XCTestCase {
    func testExample() throws {}
}
```

If not related, happy to open a new issue.

Cheers! 🙏🏼

**Comment by Enricoza** [comment]
Hi @p4checo, thank you for reporting this. It seems related to [this](https://github.com/Tealium/tealium-swift/issues/307) issue which was resolved on version `2.10.1`. Are you sure that the version you have installed on your project is the latest?

**Comment by p4checo** [comment]
hi @Enricoza 

Good shout! I was indeed testing this on `2.10.0`, and `2.10.1` appears to have fixed the issue 💪🏼  Thanks!

I am still getting the linker warning I mentioned before though. Seems pretty innocuous but maybe it's easy to fix.

![Screenshot 2023-09-25 at 11 09 52](https://github.com/Tealium/tealium-swift/assets/1391324/94e3bd18-2f30-49f0-b337-77b1b18de676)

**Comment by Enricoza** [comment]
Thank you for the quick check. We'll make sure to look at XCode 15 warnings too, although we are not even using sqlite on our library at the moment, so I have a feeling that the warning might not even be caused by us. 
We will double check that anyway.

**Comment by Enricoza** [comment]
Hi @mirko-milovanovic-vidiemme, we just released version `2.12.0` officially supporting XCode 15. So the post install script should not be needed anymore starting from this version. 

Thanks again for opening this issue and let us know if you have any others!
