### ISSUE TITLE
Carthage error (Case sensitive disks)

### ISSUE THREAD

**Issue by litoarias** [Tealium/tealium-swift#44]
Hi, I was trying to install Tealium through carthage, and I can't do it. You know it has problems with the last version? Thnks
 
  - carthage version: 0.30.1
  - xcodebuild -version: Xcode 9.3.0
  - Build version 9E145
  - Are you using --no-build? No
  - Are you using --no-use-binaries? No
  - Are you using --use-submodules? No
  - Are you using --cache-builds? No
  - Are you using --cache-builds? No

**Term output**
````
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/builder/tealium-swift.xcodeproj -scheme ios -configuration Release -derivedDataPath /Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/xr/79ghwp1x7h7606m753nr0p0h0000gn/T/tealium-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift)

````
**xcodebuild output**
````
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    cd /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/builder
    export DEVELOPER_DIR=/Users/mpu8d0000001/Downloads/Xcode.app/Contents/Developer
    export PATH="/Users/mpu8d0000001/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/mpu8d0000001/Downloads/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export SDKROOT=/Users/mpu8d0000001/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk
    /Users/mpu8d0000001/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name Tealium -O -whole-module-optimization -sdk /Users/mpu8d0000001/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -target arm64-apple-ios9.0 -g -module-cache-path /Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/ModuleCache.noindex -Xfrontend -serialize-debugging-options -embed-bitcode -swift-version 4 -I /Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/BuildProductsPath/Release-iphoneos -F /Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/BuildProductsPath/Release-iphoneos -F /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/builder/../Carthage/Build/iOS -c -num-threads 4 /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/connectivity/TealiumConnectivityModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/collect/TealiumCollect.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/devicedata/TealiumDeviceData.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/connectivity/TealiumConnectivity.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/defaultsstorage/TealiumDefaultsStorageModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/attribution/TealiumAttributionModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/dispatchqueue/TealiumPersistentDispatchQueue.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/datasource/TealiumDatasourceModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/lifecycle/TealiumLifecyclePersistentData.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumExtensions.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/appdata/TealiumAppData.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/consentmanager/TealiumConsentUserPreferences.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumInstanceManager.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumRequestArray.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/Tealium.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/filestorage/TealiumFileStorageModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumMulticastDelegate.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/appData/TealiumAppDataModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/delegate/TealiumDelegateModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/remotecommands/TealiumRemoteCommand.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/consentmanager/TealiumConsentManagerModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumUtils.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/volatiledata/TealiumVolatileDataModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/dispatchqueue/TealiumDispatchQueueConstants.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/persistentData/TealiumPersistentDataModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/consentmanager/TealiumConsentManager.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumRequests.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/dispatchqueue/TealiumDispatchQueueModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/consentmanager/TealiumConsentManagerDelegate.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/volatiledata/TealiumVolatileData.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/devicedata/TealiumDeviceDataModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumModuleConfig.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/consentmanager/TealiumConsentConstants.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/remotecommands/TealiumRemoteCommands.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumModuleResponse.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/collect/TealiumCollectModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/remotecommands/TealiumRemoteCommandsModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/autotracking/TealiumAutotrackingModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/tagmanagement/TealiumTagManagementModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/lifecycle/TealiumLifecycleModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/logger/TealiumLoggerModule.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumConfig.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/logger/TealiumLogger.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumConstants.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumModulesManager.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumModules.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/consentmanager/TealiumConsentPreferencesStorage.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/connectivity/TealiumConnectivityDelegate.swift /Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/core/TealiumReadWrite.swift -output-file-map /Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/tealium-swift.build/Release-iphoneos/ios.build/Objects-normal/arm64/ios-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/tealium-swift.build/Release-iphoneos/ios.build/Objects-normal/arm64/Tealium.swiftmodule -Xcc -I/Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/tealium-swift.build/Release-iphoneos/ios.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/tealium-swift.build/Release-iphoneos/ios.build/Tealium-generated-files.hmap -Xcc -I/Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/tealium-swift.build/Release-iphoneos/ios.build/Tealium-own-target-headers.hmap -Xcc -I/Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/tealium-swift.build/Release-iphoneos/ios.build/Tealium-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/tealium-swift.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/tealium-swift.build/Release-iphoneos/ios.build/Tealium-project-headers.hmap -Xcc -I/Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/tealium-swift.build/Release-iphoneos/ios.build/DerivedSources/arm64 -Xcc -I/Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/tealium-swift.build/Release-iphoneos/ios.build/DerivedSources -emit-objc-header -emit-objc-header-path /Users/mpu8d0000001/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/tealium-swift/1.6.0/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/tealium-swift.build/Release-iphoneos/ios.build/Objects-normal/arm64/Tealium-Swift.h -Xcc -working-directory/Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/builder
<unknown>:0: error: no such file or directory: '/Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/appData/TealiumAppDataModule.swift'
<unknown>:0: error: no such file or directory: '/Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/persistentData/TealiumPersistentDataModule.swift'
Command /Users/mpu8d0000001/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
````

**Comment by craigrouse** [comment]
@litoarias We're not aware of any issues. I will attempt to rebuild with Carthage and come back to you ASAP.

**Comment by litoarias** [comment]
Hi @craigrouse , I found the possible problem, I downloaded the project and here are some files that xcode not found, and that is the crash for me installing though Carthage

![screen shot 2018-07-24 at 08 29 56](https://user-images.githubusercontent.com/7962872/43120942-3d8a30c2-8f1c-11e8-959f-19247c465e5e.png)

**OUTPUT TERM ERROR**
````
<unknown>:0: error: no such file or directory: '/Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/appData/TealiumAppDataModule.swift'
<unknown>:0: error: no such file or directory: '/Users/mpu8d0000001/PROJECTS/ModelBank/INGRubik/Rhea/Carthage/Checkouts/tealium-swift/tealium/persistentData/TealiumPersistentDataModule.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
````

I hope advantage you for solve problem

**Comment by craigrouse** [comment]
@litoarias could you check for me if your Mac's hard disk has case-sensitivity enabled on the filesystem? The default is for this to be off. I'm wondering if you have it enabled.

![image](https://user-images.githubusercontent.com/4818525/43129562-a23d0f52-8f2c-11e8-8902-65d9e9a05288.png)

**Comment by craigrouse** [comment]
@litoarias I have now done 2 tests with Carthage, and I got no build errors or crashes. I strongly suspect you have case-sensitivity enabled. I will update the project to remove the camelCase directory names, which is what seems to be causing the problem for you.

**Comment by litoarias** [comment]
Yes, I have case-sensitivity to YES, and it's the way to use Disk configuration of 99% developers. I no understand for what should change it.

**Comment by litoarias** [comment]
Yes, you are right. It seems to be working in another computer with `case sensitive = NO`. Thanks!

**Comment by craigrouse** [comment]
@litoarias can you please test again on your machine? I just did a small hotfix to change the case of those 2 folders in the Xcode project. Hopefully this should work now on case-sensitive filesystems.

**Comment by litoarias** [comment]
The issue persists when downloading it through Carthage.. but when downloading the project manually works fine... I did clean carthage cache just in case.. but didn't work

**Comment by craigrouse** [comment]
@litoarias I just realised I forgot to edit the "release" on GitHub, which is where Carthage pulls files from. Stand by.. I'm creating a new release now.

**Comment by craigrouse** [comment]
@litoarias OK - that's done now. Try updating Carthage again (clean cache). If you still have trouble, force it to use version "1.6.1" in your Cartfile.

**Comment by craigrouse** [comment]
@litoarias One other thing... hopefully you found all the docs you need to get started, but here are some links in case you need them:

https://community.tealiumiq.com/t5/Tealium-for-Swift/Introduction-to-the-Tealium-Swift-Library/ta-p/20032

Make sure you also read about the Consent Manager module: https://community.tealiumiq.com/t5/Tealium-for-Swift/Swift-Module-Consent-Manager/ta-p/24572

If you don't either set a consent status or disable the module, you will not see any tracking calls.

**Comment by litoarias** [comment]
Yes now works fine, but for me, it's a temporal solution because I will have problems in the future. Thanks a lot for helping me to find this complex issue, I think I would never be had found that type of problem alone... 

By the way, thanks for the information and your bits of help, the documentation is very helpful and complete...

**Comment by craigrouse** [comment]
Good to hear @litoarias. Happy we could resolve this quickly for you. Feel free to post on the Tealium Learning Community or get in touch with support if you have any issues with the implementation.
